### ISSUE TITLE
Getting NoCLassDefFoundError

### ISSUE THREAD

**Issue by archanarathnam** [g-tiwari/VoiceAutomationClient#2]
java.lang.NoClassDefFoundError: com/sun/jersey/api/client/config/ClientConfig
	at in.co.gauravtiwari.voice.client.VoiceAutomationClient.<init>(VoiceAutomationClient.java:51)
	at com.nttdata.testframework.pagefactory.novum.mobileapp.AuraPage.playInternetVoiceFile(xxxx.java:1240)
	at com.nttdata.testframework.novum.cucumber.glue.stepdefinitions.AuraSteps.voiceCommandIsProvidedAndAuraResponseIsVerified(xxxx.java:320)
	at ✽.voice command is provided and aura response is verified(C:/Users/xxxxxxxxxxxxxxxxx:8)
Caused by: java.lang.ClassNotFoundException: com.sun.jersey.api.client.config.ClientConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at in.co.gauravtiwari.voice.client.VoiceAutomationClient.<init>(VoiceAutomationClient.java:51)
	at com.nttdata.testframework.pagefactory.novum.mobileapp.AuraPage.playInternetVoiceFile(AuraPage.java:1240)
	at com.nttdata.testframework.novum.cucumber.glue.stepdefinitions.AuraSteps.voiceCommandIsProvidedAndAuraResponseIsVerified(AuraSteps.java:320)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:31)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:25)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:37)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:40)
	at cucumber.api.TestStep.executeStep(TestStep.java:102)
	at cucumber.api.TestStep.run(TestStep.java:83)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.Runtime.runFeature(Runtime.java:119)
	at cucumber.runtime.Runtime.run(Runtime.java:104)
	at cucumber.api.cli.Main.run(Main.java:36)
	at cucumber.api.cli.Main.main(Main.java:18)

**Comment by archanarathnam** [comment]
Please help me in getting this resolved

**Comment by g-tiwari** [comment]
@archanarathnam 
Can you please help me with repro steps and OS configuration you are using?

**Comment by archanarathnam** [comment]
I am using appium with java
OS - android
I want to click on a button and then input voice to the native app so that it plays the audio file. BUt When I try to run the script, I am getting this error.

I have started the voiceautomationserver and then given VoiceAutomationServerEndpoint, audio file path and api key.
Please let me know if I have to do any other changes

**Comment by g-tiwari** [comment]
Sorry for the confusion, by OS I meant the machine OS where you are running your code?
From logs, I guess its Windows.

Can you please also paste the few lines of code here where it is giving the exception?

**Comment by archanarathnam** [comment]
Hi 
Thanks for your reply. Yes I am using Windows. 

 public static void playInternetVoiceFile(){

        //Start the server on your target machine by command java -jar VoiceAuotmationServer.jar
        System.setProperty("VoiceAutomationServerEndpoint","http://xxxxxxx.uk.pri.xx.com:9090");
        //Signup to voicerss and get your api key
        System.setProperty("VoiceRssKey","3f30f336ad0543febe0324415310a3c0");
        Voice voice = new Voice("C:\\Users\\Rathnaa1\\Music\\keep my number.aac");

        try {
            VoiceAutomationClient voiceAutomationClient = new VoiceAutomationClient();
            voiceAutomationClient.load(voice);
            voiceAutomationClient.play(voice);
            logger.info(voice.getFilename());
            logger.info(voice.getText());
            logger.info(voice.getVoiceName());
            logger.info(voice.getVoiceLanguage().toString());
        }catch (ClientOperationException e){
            e.printStackTrace();
        }catch (Exception ex){
            ex.printStackTrace();
        }
    }


-----
console output -
INFO  2018-11-22 10:34:22,808 [main] AuraPage:clickOnAura(516): The Aura icon is clickedDEBUG 2018-11-22 10:34:22,810 [main] PageObject:setContext(79): setting context to: NATIVE_APP
DEBUG 2018-11-22 10:34:24,478 [main] PageObject:clickOn(96): Clicking on 
java.lang.NoClassDefFoundError: com/sun/jersey/api/client/config/ClientConfig
	at in.co.gauravtiwari.voice.client.VoiceAutomationClient.<init>(VoiceAutomationClient.java:51)
	at com.nttdata.testframework.pagefactory.novum.mobileapp.AuraPage.playInternetVoiceFile(AuraPage.java:1240)
	at com.nttdata.testframework.novum.cucumber.glue.stepdefinitions.AuraSteps.voiceCommandIsProvidedAndAuraResponseIsVerified(AuraSteps.java:320)
	at ✽.voice command is provided and aura response is verified(C:/Users/Rathnaa1/IdeaProjects/novumo2ask/src/test/resources/features/regressionTest/try.feature:8)
Caused by: java.lang.ClassNotFoundException: com.sun.jersey.api.client.config.ClientConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at in.co.gauravtiwari.voice.client.VoiceAutomationClient.<init>(VoiceAutomationClient.java:51)
	at com.nttdata.testframework.pagefactory.novum.mobileapp.AuraPage.playInternetVoiceFile(AuraPage.java:1240)
	at com.nttdata.testframework.novum.cucumber.glue.stepdefinitions.AuraSteps.voiceCommandIsProvidedAndAuraResponseIsVerified(AuraSteps.java:320)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:31)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:25)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:37)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:40)
	at cucumber.api.TestStep.executeStep(TestStep.java:102)
	at cucumber.api.TestStep.run(TestStep.java:83)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.Runtime.runFeature(Runtime.java:119)
	at cucumber.runtime.Runtime.run(Runtime.java:104)
	at cucumber.api.cli.Main.run(Main.java:36)
	at cucumber.api.cli.Main.main(Main.java:18)

DEBUG 2018-11-22 10:34:26,136 [main] AndroidApplicationDriver:setContext(117): setting the context :NATIVE_APP
DEBUG 2018-11-22 10:34:26,558 [main] AndroidApplicationDriver:minimiseApp(152): minimising app
Failed scenarios:
C:/Users/Rathnaa1/IdeaProjects/novumo2ask/src/test/resources/features/regressionTest/try.feature:4 # Knowledge Base Voice

**Comment by archanarathnam** [comment]
Please let me know if any other information is required.

**Comment by g-tiwari** [comment]
Hey @archanarathnam ,
On windows, there is an existing issue on which I am working on. Fix would be there very soon.
Also, there is one more thing. 
Can you add a forward slash in url in your below line after port number -
System.setProperty("VoiceAutomationServerEndpoint","http://xxxxxxx.uk.pri.xx.com:9090/")

After doing this, try again and send the stacktrace here, I believe you will see a separate stacktrace

**Comment by archanarathnam** [comment]
Hi, 

Thanks for your reply. I tried even with the forward slash. It shows the same error.

**Comment by archanarathnam** [comment]
Any updates please.

**Comment by g-tiwari** [comment]
Hey @archanarathnam ,
Support for .aac file is not there.. It currently support only mp3 and wav file
Can you try again with one of these file

**Comment by g-tiwari** [comment]
> Any updates please.

Hey Archna,
This has been fixed now, Please use VoiceAutomationServer latest version i.e. 1.0.1
Reopen the issue in case you again face issue

**Comment by archanarathnam** [comment]
I am getting Error: Invalid or corrupt jarfile VoiceAutomationServer-1.0.1.jar when I start the server in the cmd prompt.

**Comment by g-tiwari** [comment]
It looks like you did not downloaded it properly.
Jar file size should be 5 MB atleast. Please check and re-download . Link - https://github.com/g-tiwari/VoiceAutomationServer/raw/master/VoiceAutomationServer-1.0.1.jar

**Comment by archanarathnam** [comment]
Thanks now I am able to download.

**Comment by archanarathnam** [comment]
Though I have added the jar file in File->Project Structure, and change the scope to "test", I am getting the below error -
package in.co.gauravtiwari.voice.client does not exist

Could you please let me know if anything else needs to be done. 

Note- Not able to resolve dependency from pom.xml if I add as a dependency so I have chosen the option to add as a jar.

**Comment by g-tiwari** [comment]
Hey Archana, 
this is a generic basic IDE and jar issue, please google and get help from your collegue. This problem is not specific to this library.
I would suggest to use the maven dependency in pom. Client and server are two seperate jar files, the file which you downloaded is not supposed to be added in IDE classpath

**Comment by archanarathnam** [comment]
Hi Gaurav,

Thanks for your support. I have added the client, server, everything looks fine, When I run the text to speech function, it is saying, "in.co.gauravtiwari.voice.clientresources.ClientOperationException: Connection refused: connect".

Note - VoiceAutomationServer is running and the logs are given below-
INFO [main] (VoiceAutomationServer.java:128) - Voice Automation server started at http://xxxxxxxx.xx.xx.xx.com:9090/
 INFO [Grizzly(2)] (VoiceAutomationServerAPI.java:54) - entered load controller
 INFO [Grizzly(2)] (VoiceAutomationServerAPI.java:57) - file url https://api.voicerss.org/?key=f2f607022d7f4c8e8e82b9b3cd454565&c=WAV&hl=en-us&src=Hey+Google%2C+whats+the+current+time
 INFO [Grizzly(2)] (VoiceAutomationServerAPI.java:64) - exception loading file

**Comment by archanarathnam** [comment]
Thanks Gaurav. It is working fine.
